# version: "3.8"

services:
  backend:
    build:
      context: . # Root directory
      dockerfile: backend/StoreBackend/Dockerfile
    ports:
      - "5000:80"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
